# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build and Push to Docker Hub'
  inputs:
    containerRegistry: 'Docker Hub - kovadocker'
    repository: 'kovadocker/dashboard-backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    
- task: SSH@0
  displayName: Deploy
  inputs:
    sshEndpoint: 'SSH - werik.com  - azuredevops'
    runOptions: 'commands'
    commands: |
      docker ps -f name=dashboard-backend    
      docker pull kovadocker/dashboard-backend:${{ BuildID }}
      docker stop dashboard-backend
      docker rm dashboard-backend
      docker run --name=dashboard-backend --restart=always -p 8888:8080 -d kovadocker/dashboard-backend:${{ BuildID }}
    readyTimeout: '20000'